# Generated by Django 4.2.29 on 2026-03-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_seed_orders_catalogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
    ]
