# Generated by Django 4.2.29 on 2026-03-22 04:25

from django.db import migrations


def set_protected_flags(apps, schema_editor):
    PaymentMethod = apps.get_model('orders', 'PaymentMethod')
    protected_names = ['EFECTIVO', 'TRANSFERENCIA', 'PAGO CONTRA ENTREGA']
    PaymentMethod.objects.filter(name__in=protected_names).update(is_protected=True)

def reverse_protected_flags(apps, schema_editor):
    PaymentMethod = apps.get_model('orders', 'PaymentMethod')
    protected_names = ['EFECTIVO', 'TRANSFERENCIA', 'PAGO CONTRA ENTREGA']
    PaymentMethod.objects.filter(name__in=protected_names).update(is_protected=False)

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_paymentmethod_is_protected'),
    ]

    operations = [
        migrations.RunPython(set_protected_flags, reverse_protected_flags),
    ]
