# Generated by Django 4.2.30 on 2026-04-24 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderitem_base_quantity_and_more'),
        ('orders', '0007_protect_default_payment_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notifications', to='orders.order')),
            ],
            options={
                'db_table': 'order_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
