# Generated by Django 4.2.30 on 2026-05-17 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_keep_only_admin_role'),
        ('orders', '0008_ordernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='orders.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='orderitemstatushistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.user'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.user'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.user'),
        ),
    ]
