# Generated by Django 4.2.29 on 2026-03-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('RETAIL', 'Minorista'), ('WHOLESALE', 'Mayorista')], default='RETAIL', max_length=20),
        ),
    ]
