# Generated by Django 4.2.29 on 2026-03-16 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'business_units',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('factor', models.SmallIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transaction_types',
            },
        ),
        migrations.CreateModel(
            name='UoM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'uoms',
            },
        ),
        migrations.CreateModel(
            name='UoMConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(decimal_places=4, max_digits=10)),
                ('from_uom', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='conversions_from', to='inventory.uom')),
                ('to_uom', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='conversions_to', to='inventory.uom')),
            ],
            options={
                'db_table': 'uom_conversions',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.transactiontype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': 'inventory_transactions',
            },
        ),
    ]
