# Generated by Django 4.2.29 on 2026-03-16 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='uomconversion',
            unique_together={('from_uom', 'to_uom')},
        ),
    ]
