# Generated by Django 4.2.30 on 2026-04-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rework_inventory_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='conversion_multiplier',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
    ]
