# Generated by Django 4.2.30 on 2026-05-17 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_keep_only_admin_role'),
        ('inventory', '0005_alter_inventorytransaction_base_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.user'),
        ),
    ]
